# Generated by Django 3.2.8 on 2021-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('alternate_number', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
                ('heighest_qualification', models.CharField(max_length=20)),
                ('work', models.CharField(choices=[(1, 'it'), (2, 'nonit'), (3, 'Pharma'), (4, 'Bussiness'), (5, 'selfemployee')], max_length=15)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
